# Generated by Django 4.1.5 on 2023-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_code', models.CharField(max_length=500)),
            ],
        ),
    ]
